import Link from "next/link";

function ComlyLogo() {
  return (
    <svg width="26" height="26" viewBox="0 0 100 110" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M50 4 C54 4 57 6 59.5 10 L93 68 C97 74 97 80 93.5 85 C90 90 84 93 77 93 L23 93 C16 93 10 90 6.5 85 C3 80 3 74 7 68 L40.5 10 C43 6 46 4 50 4Z"
        fill="#1a1a2e"
      />
      <path
        d="M28 72 C32 62 44 56 58 60 C66 62.5 70 67 68 70 C66 73 60 72 52 69 C44 66 36 68 32 74 C30 77 28 75 28 72Z"
        fill="url(#swooshGradT)"
      />
      <defs>
        <linearGradient id="swooshGradT" x1="28" y1="65" x2="70" y2="65" gradientUnits="userSpaceOnUse">
          <stop offset="0%" stopColor="#5b21b6" />
          <stop offset="100%" stopColor="#a855f7" />
        </linearGradient>
      </defs>
    </svg>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Nav */}
      <header className="border-b border-[#f0f0f0] px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
            <ComlyLogo />
            <span className="font-bold text-[#0a0a0a] text-base">Comly</span>
          </Link>
          <Link href="/" className="text-sm text-[#6b6b6b] hover:text-[#0a0a0a] transition-colors">
            ← Back to home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-12">
          <p className="text-xs font-bold uppercase tracking-widest text-[#5B2D91] mb-3">Legal</p>
          <h1 className="text-4xl font-bold text-[#0a0a0a] mb-4">Terms of Use</h1>
          <p className="text-[#6b6b6b]">Last updated: May 9, 2026</p>
        </div>

        <div className="prose prose-gray max-w-none space-y-10 text-[15px] leading-relaxed text-[#3a3a3a]">

          <section>
            <p>
              Please read these Terms of Use (&ldquo;Terms&rdquo;) carefully before using the Comly AI platform
              (&ldquo;Service&rdquo;) operated by Comly AI (&ldquo;Comly&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;).
            </p>
            <p className="mt-4">
              By accessing or using the Service, you agree to be bound by these Terms. If you do not agree to
              any part of these Terms, you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">1. Description of Service</h2>
            <p>
              Comly provides an AI visibility audit platform that analyses how well a brand appears in responses
              generated by large language models (LLMs) such as ChatGPT, Gemini, Claude, and Perplexity. The
              Service includes audit reports, engagement tooling, optimisation recommendations, and related features.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">2. Eligibility</h2>
            <p>
              You must be at least 16 years old and have the legal capacity to enter into a binding agreement
              to use the Service. By using the Service, you represent that you meet these requirements.
              If you are using the Service on behalf of an organisation, you represent that you have the
              authority to bind that organisation to these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">3. Accounts</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>You must notify us immediately at{" "}
                <a href="mailto:rayanebenchaalal@gmail.com" className="text-[#5B2D91] hover:underline">rayanebenchaalal@gmail.com</a>{" "}
                if you suspect unauthorised access to your account.
              </li>
              <li>We reserve the right to terminate accounts that violate these Terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">4. Acceptable Use</h2>
            <p className="mb-4">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws or regulations.</li>
              <li>Submit URLs or brand data belonging to a third party without their authorisation.</li>
              <li>Attempt to reverse-engineer, decompile, or extract source code from the Service.</li>
              <li>Use automated tools (bots, scrapers) to access the Service in a manner that exceeds reasonable personal use.</li>
              <li>Interfere with or disrupt the integrity or performance of the Service or its underlying infrastructure.</li>
              <li>Use the Service to generate or distribute spam, misinformation, or harmful content.</li>
              <li>Resell, sublicense, or commercially exploit the Service without our prior written consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">5. Subscription &amp; Payment</h2>
            <p className="mb-4">
              Access to Comly is currently available under an <strong>Early Access plan at $49/month</strong>.
              There is no free plan or free trial. You must have an active paid subscription to access the
              Service and run audits.
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Subscriptions are billed monthly in advance.</li>
              <li>All fees are non-refundable except where required by applicable law.</li>
              <li>We reserve the right to change pricing with 30 days&apos; notice to subscribers. Continued use after the notice period constitutes acceptance of the new pricing.</li>
              <li>Failure to pay will result in suspension or termination of your account and loss of access to the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">6. Intellectual Property</h2>
            <p className="mb-4">
              <strong>Our content.</strong> The Service, including its design, code, text, graphics, and underlying
              technology, is owned by Comly and protected by intellectual property laws. You may not copy,
              modify, or distribute it without our express written permission.
            </p>
            <p>
              <strong>Your content.</strong> You retain ownership of the brand data and profile information you
              submit. By submitting it, you grant Comly a limited, non-exclusive licence to use it solely for
              the purpose of providing the Service to you.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">7. Third-Party Services</h2>
            <p>
              The Service integrates with third-party AI providers (OpenAI, Google), payment processors (Stripe),
              and other services. Your use of those services is governed by their respective terms and privacy
              policies. We are not responsible for the content, availability, or practices of any third-party service.
            </p>
            <p className="mt-4">
              AI-generated audit results are produced by third-party language models. We do not guarantee the
              accuracy, completeness, or fitness for any particular purpose of AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">8. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EITHER
              EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
              PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED,
              ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">9. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, COMLY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING
              OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE
              POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY TO YOU SHALL NOT EXCEED THE AMOUNT PAID BY YOU
              TO COMLY IN THE 12 MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">10. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless Comly and its officers, directors, employees,
              and agents from any claims, damages, losses, or expenses (including reasonable legal fees) arising
              from your use of the Service, your violation of these Terms, or your infringement of any third-party rights.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">11. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time, with or without cause or notice,
              including for violation of these Terms. Upon termination, your right to use the Service ceases
              immediately. Provisions that by their nature should survive termination will do so, including
              Sections 6, 8, 9, and 10.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">12. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will provide at least 14 days&apos; notice
              of material changes via email or a notice within the Service. Continued use of the Service after
              changes take effect constitutes your acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">13. Governing Law</h2>
            <p>
              These Terms are governed by and construed in accordance with applicable law. Any disputes arising
              under these Terms shall be resolved through binding arbitration or in the courts of competent
              jurisdiction, as applicable.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a0a0a] mb-4">14. Contact</h2>
            <p>
              Questions about these Terms? Contact us at:
            </p>
            <address className="not-italic mt-4 bg-[#fafafa] border border-[#e5e5e5] rounded-xl px-5 py-4 text-sm">
              <strong>Comly AI</strong><br />
              Email:{" "}
              <a href="mailto:rayanebenchaalal@gmail.com" className="text-[#5B2D91] hover:underline">rayanebenchaalal@gmail.com</a>
            </address>
          </section>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-[#f0f0f0] py-8 px-6 mt-8">
        <div className="max-w-3xl mx-auto flex items-center justify-between flex-wrap gap-4">
          <p className="text-xs text-[#aaaaaa]">© 2026 Comly AI. All rights reserved.</p>
          <div className="flex items-center gap-6">
            <Link href="/privacy" className="text-xs text-[#6b6b6b] hover:text-[#0a0a0a] transition-colors">Privacy Policy</Link>
            <Link href="/terms" className="text-xs text-[#5B2D91] font-medium">Terms of Use</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
